#ifndef _GATESTEPPER_H_
#define _GATESTEPPER_H_

#include "driver/gpio.h"

#define HWCONFIG_STEPPER_DIR_PIN GPIO_NUM_33
#define HWCONFIG_STEPPER_STEP_PIN GPIO_NUM_25
#define HWCONFIG_STEPPER_SLP_PIN GPIO_NUM_26

void GATESTEPPER_Init();

bool GATESTEPPER_MoveTo(int32_t s32Ticks);

#endif