#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_ESP_WIFI_SSID_BASE ("SGU-Ring-Fact-%02X%02X%02X")
#define CONFIG_ESP_WIFI_PASS      ("")
#define CONFIG_ESP_WIFI_CHANNEL   1
#define CONFIG_MAX_STA_CONN       5

#define CONFIG_HOLDPOWER_PIN GPIO_NUM_26
#define CONFIG_HOLDPOWER_DELAY_MS 300*1000

// GUI
#define CONFIG_SWITCH_PIN GPIO_NUM_21
#define CONFIG_SWITCH_HOLDDELAY_MS 1500

// WS1228 as sanity led
#define CONFIG_WS1228B_PIN GPIO_NUM_18
#define CONFIG_WS1228B_LEDCOUNT (45)

#endif