name: ci

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build (ring-factory)
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.3
        path: ./Source/ring-factory
        target: esp32

    - name: Build (ring-fw)
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.3
        path: ./Source/ring-fw
        target: esp32

    - name: Build (base-fw)
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.3
        path: ./Source/base-fw
        target: esp32
