name: ci

on:
  push:
    branches:
      - 'pinkymaxou-patch-1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build (ring-factory)
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.3
        path: ./Source/ring-factory
        target: esp32

