name: ci

on:
  push:
    branches:
      - 'pinkymaxou-patch-1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build (ring-factory)
      uses: docker/build-push-action@v2
      with:
        context: ./Source/ring-factory
        tags: stargate-sgu:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
